puts "H      H  EEEEE  L      L        OOO    SSSSS  H      H  IIIII  M     M  U     U"
puts "H      H  E       L      L       O   O  S       H      H    I    MM   MM  U     U"
puts "HHHHHHHH  EEEE    L      L       O   O  SSSSS   HHHHHHH    I    M M M M  U     U"
puts "H      H  E       L      L       O   O      S   H      H    I    M  M  M  U     U"
puts "H      H  EEEEE  LLLLL  LLLLL    OOO   SSSSS   H      H  IIIII  M     M   UUUUU "
